#!/bin/csh -f
#
# install lisp files
#
# Copyright (c) 1991, 1992, 1993 Xerox Corporation.  All Rights Reserved.  
# 
# Unlimited use, reproduction, and distribution of this software is
# permitted.  Any copy of this software must include both the above
# copyright notice of Xerox Corporation and this paragraph.  Any
# distribution of this software must comply with all applicable United
# States export control laws.  This software is made available AS IS,
# and XEROX CORPORATION DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
# INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS FOR A PARTICULAR PURPOSE, AND NOTWITHSTANDING ANY OTHER
# PROVISION CONTAINED HEREIN, ANY LIABILITY FOR DAMAGES RESULTING FROM
# THE SOFTWARE OR ITS USE IS EXPRESSLY DISCLAIMED, WHETHER ARISING IN
# CONTRACT, TORT (INCLUDING NEGLIGENCE) OR STRICT LIABILITY, EVEN IF
# XEROX CORPORATION IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
# 

set bext = $1
shift
set destdir = $1
shift
set install = $1
shift

echo install is $install
echo bext is $bext
echo destdir is $destdir

foreach file ( $* )
	if ( -r ${file:r}.${bext} ) then
		echo "${install} -m 444 ${file:r}.${bext} ${destdir}/lisp"
		${install} -m 444 ${file:r}.${bext} ${destdir}/lisp
	endif
end
