/** $Id: bank3.idl,v 1.3 1999/08/03 01:58:58 janssen Exp $
 BeginILUCopyright

 Copyright (c) 1991-1999 Xerox Corporation.  All Rights Reserved.

 Unlimited use, reproduction, modification, and distribution of this
 software and modified versions thereof is permitted.  Permission is
 granted to make derivative works from this software or a modified
 version thereof.  Any copy of this software, a modified version
 thereof, or a derivative work must include both the above copyright
 notice of Xerox Corporation and this paragraph.  Any distribution of
 this software, a modified version thereof, or a derivative work must
 comply with all applicable United States export control laws.  This
 software is made available AS IS, and XEROX CORPORATION DISCLAIMS ALL
 WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION THE
 IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 PURPOSE, AND NOTWITHSTANDING ANY OTHER PROVISION CONTAINED HEREIN, ANY
 LIABILITY FOR DAMAGES RESULTING FROM THE SOFTWARE OR ITS USE IS
 EXPRESSLY DISCLAIMED, WHETHER ARISING IN CONTRACT, TORT (INCLUDING
 NEGLIGENCE) OR STRICT LIABILITY, EVEN IF XEROX CORPORATION IS ADVISED
 OF THE POSSIBILITY OF SUCH DAMAGES.

 EndILUCopyright
*/
/* Last edited by Mike Spreitzer October 9, 1998 10:39 am PDT */

///////////////////////////////////////////////////////////////////////
//
// File Name: bank3.idl 
//
// Contents: Header file for step3 of the Progressive Sample Applications
//
//  ----------------------------------------------------------------------
// !  Copyright Hewlett-Packard Company 1992-1996.  All Rights Reserved.  !
// !  An unpublished and CONFIDENTIAL work.  Reproduction, adaptation, or !
// !  translation without prior written permission is prohibited except   !
// !  as allowed under the copyright laws.                                !
//  ----------------------------------------------------------------------
//
///////////////////////////////////////////////////////////////////////

module BankApp{

    interface Account { 
	
		readonly attribute string ID;
		readonly attribute float balance;

  	};

    interface Bank {

    	    	readonly attribute string name;

            	Account create_account (
                		in string ID,
                		in float deposit
        	                );
    	};

    interface Factory {

	Bank create_bank(in string name);
    };
	
};







