.\" Copyright (c) 1991, 1992, 1993 Xerox Corporation.  All Rights Reserved.  
.\" Copyright (c) 1997 Siemens Corporate Research.  All Rights Reserved.  
.\" 
.\" Unlimited use, reproduction, and distribution of this software is
.\" permitted.  Any copy of this software must include both the above
.\" copyright notice of Xerox Corporation and this paragraph.  Any
.\" distribution of this software must comply with all applicable United
.\" States export control laws.  This software is made available AS IS,
.\" and XEROX CORPORATION DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
.\" INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS FOR A PARTICULAR PURPOSE, AND NOTWITHSTANDING ANY OTHER
.\" PROVISION CONTAINED HEREIN, ANY LIABILITY FOR DAMAGES RESULTING FROM
.\" THE SOFTWARE OR ITS USE IS EXPRESSLY DISCLAIMED, WHETHER ARISING IN
.\" CONTRACT, TORT (INCLUDING NEGLIGENCE) OR STRICT LIABILITY, EVEN IF
.\" XEROX CORPORATION IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
.\" 
.\" $Id: scheme-stubber.1,v 1.2 1997/09/04 01:48:08 janssen Exp $
.\" scheme-stubber.1
.TH SCHEME-STUBBER 1 "11 May 1997"
.SH NAME
scheme-stubber \- generate ILU stubs for the Scheme language
.SH SYNOPSIS
\fBscheme-stubber\fR \fI[options]\fR \fIISLFILE\fR [ \fI...ISLFILES\fR ]
.SH DESCRIPTION
.B scheme-stubber
generates the Scheme client and server code libraries for the
interface defined in \fIISLFILE\fR, which should be a file
containing an ISL specification of the interface.  If no directory
is specified as part of \fIISLFILE\fR, the stubber will search
for the file in the list of directories specified by the
environment variable \fCILUPATH\fR.  If no file extension is
specified for \fIISLFILE\fR, the extension "\fC.isl\fR" is assumed.
.sp
If the interface being stubbed is called "\fCfoo\fR", two
files called "\fCfoo.scm\fR" (which contains the actual library code
for client-side applications), and "\fCfoo-server-stubs.scm\fR" (which contains
additional code for use in servers exporting the interface "\fCfoo\fR"), will
be created.
.sp
.SH OPTIONS
.sp
\fI-I path\fR - Specify an include path to search for imported interfaces.
.sp
\fI-removefirst\fR - The stubber will attempt to remove any old versions of
the stub files before generating the new ones.
.sp
\fI-dir\fR - Directory to stick the generated stubs in.
.sp
\fI-renames\fR - A file which contains user definable mappings of type and
method names.
.sp
\fI-cname\fR - The basename to give the surrogate object definitions file.
.sp
\fI-sname\fR - The basename to give the server stubs file.
.SH EXAMPLES
.LP
.RS
57 % \fBscheme-stubber foo.isl\fR
.br
code for interface foo to ./foo.scm...
.br
code for server stubs of interface foo to ./foo-server-stubs.scm...
.br
58 %
.RE
.SH "ENVIRONMENT VARIABLES"
The environment variable "ILUPATH" is consulted to find referenced
interfaces.  It should consist of a sequence of colon-separated directories,
which contain interface specifications in the form of files
with names like \fI<interface-name>\fC.isl\fR.
.SH "SEE ALSO"
\fClisp-stubber(1), class-stubber(1), ILU(1)\fR
.sp
\fI``Using ILU with SCHEME''\fR
.SH "AUTHOR"
Bill Nell, bnell@scr.siemens.com
