.\" Copyright (c) 1991, 1992, 1993 Xerox Corporation.  All Rights Reserved.  
.\" 
.\" Unlimited use, reproduction, and distribution of this software is
.\" permitted.  Any copy of this software must include both the above
.\" copyright notice of Xerox Corporation and this paragraph.  Any
.\" distribution of this software must comply with all applicable United
.\" States export control laws.  This software is made available AS IS,
.\" and XEROX CORPORATION DISCLAIMS ALL WARRANTIES, EXPRESS OR IMPLIED,
.\" INCLUDING WITHOUT LIMITATION THE IMPLIED WARRANTIES OF MERCHANTABILITY
.\" AND FITNESS FOR A PARTICULAR PURPOSE, AND NOTWITHSTANDING ANY OTHER
.\" PROVISION CONTAINED HEREIN, ANY LIABILITY FOR DAMAGES RESULTING FROM
.\" THE SOFTWARE OR ITS USE IS EXPRESSLY DISCLAIMED, WHETHER ARISING IN
.\" CONTRACT, TORT (INCLUDING NEGLIGENCE) OR STRICT LIABILITY, EVEN IF
.\" XEROX CORPORATION IS ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.
.\" 
.\" $Id: lisp-stubber.1,v 1.3 1996/11/08 03:57:23 janssen Exp $
.\" lisp-stubber.1
.TH LISP-STUBBER 1 "11 March 1993"
.SH NAME
lisp-stubber \- generate ILU stubs for the Common Lisp language
.SH SYNOPSIS
\fBlisp-stubber\fR \fIISLFILE\fR [ \fI...ISLFILES\fR ]
.SH DESCRIPTION
.B lisp-stubber
generates the Common Lisp client and server code libraries for the
interface defined in \fIISLFILE\fR, which should be a file
containing an ISL specification of the interface.  If no directory
is specified as part of \fIISLFILE\fR, the stubber will search
for the file in the list of directories specified by the
environment variable \fCILUPATH\fR.  If no file extension is
specified for \fIISLFILE\fR, the extension "\fC.isl\fR" is assumed.
.sp
If the interface being stubbed is called \fCfoo\fR, three
files called "\fCfoo-sysdcl.lisp\fR" (which contains pdefsys description
of the lisp module for support of \fCfoo\fR), "\fCfoo-basics.lisp\fR"
(which contains the actual library code
for client-side applications, including class and type definitions),
and "\fCfoo-server-procs.lisp\fR" (which contains
additional code for use in servers exporting the interface \fCfoo\fR -- mainly
definitions of implementation classes), will be created.
.SH EXAMPLES
.LP
.RS
\fC57 % lisp-stubber foo.isl
.br
lisp-stubber foo.isl
.br
basics file for interface foo to foo-basics.lisp...
.br
server stubs for interface foo to foo-server-procs.lisp...
.br
sysdcl for interface foo to foo-sysdcl.lisp...\fR
.br
58 %
.SH "ENVIRONMENT VARIABLES"
The environment variable "ILUPATH" is consulted to find referenced
interfaces.  It should consist of a sequence of colon-separated directories,
which contain interface specifications in the form of files
with names like \fI<interface-name>\fC.isl\fR.
.SH "SEE ALSO"
\fCc++-stubber(1), class-stubber(1), ILU(1)\fR
.sp
\fI``Using ILU with Common Lisp''\fR
.SH "AUTHOR"
.RE
Bill Janssen
